"""
Modify the starter code below to create your own cool drawing
and then Pull Request it to your instructor. Make sure you
keep the last two lines of code. Your first and last name must be written on your art.
The last line keeps the window open until you click to close.

Turtle Documentation: https://docs.python.org/3.3/library/turtle.html?highlight=turtle

"""
import turtle
tina = turtle.Turtle()
tina.shape('turtle')
tommy = turtle.Turtle()
tommy.shape('turtle')
tommy.color('grey')
tommy.shape('turtle')

tommy.goto(200, 200)
tommy.begin_fill()
tommy.goto(200, -200)
tommy.goto(-200, -200)
tommy.goto(-200, 200)
tommy.goto(200, 200)
tommy.end_fill()
tommy.goto(0, 0)
tommy.color("black")
tina.penup()
tina.goto(0, -180)
tina.pendown()
tina.begin_fill()
tina.circle(180)
tina.color('white')
tina.end_fill()
tina.goto(0, 130)
tina.color("black")
tina.write('12', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(0, 0)
tina.goto(70, 110)
tina.color("black")
tina.write('1', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(70, 90)
tina.goto(0, 0)
tina.goto(120, 60)
tina.color("black")
tina.write('2', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(120, 45)
tina.goto(0, 0)
tina.goto(145, -15)
tina.color("black")
tina.write('3', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(145, -30)
tina.goto(0, 0)
tina.color('white')
tina.goto(117, -90)
tina.color("black")
tina.write('4', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(110, -93)
tina.goto(0, 0)
tina.goto(70, -140)
tina.color("black")
tina.write('5', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(50, -150)
tina.goto(0, 0)
tina.goto(0, -150)
tina.color("black")
tina.write('6', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(-50, -150)
tina.goto(0, 0)
tina.goto(-70, -140)
tina.color("black")
tina.write('7', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(-60, -130)
tina.goto(0, 0)
tina.goto(-130, -80)
tina.color("black")
tina.write('8', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(-100, -85)
tina.goto(0, 0)
tina.goto(-145, -15)
tina.color("black")
tina.write('9', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(-145, -20)
tina.goto(0, 0)
tina.color('white')
tina.goto(-120, 54)
tina.color("black")
tina.write('10', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(-110, 55)
tina.goto(0, 0)
tina.goto(-70, 110)
tina.color("black")
tina.write('11', font=("Arial", 30, "normal"))
tina.color('white')
tina.goto(0, 0)
tina.pensize()
tina.color("black")
tina.goto(0, -65)
tina.goto(0, 0)
tina.color("black")
tina.goto(100, 50)
tina.goto(0, 0)
tina.color("white")
tina.goto(-40, 50)
tina.color("blue")

tina.write('Rachel Linthicum', font=("Arial", 16, "normal"))  # signs your name to your art
# Keeps pycharm window open so we can see the drawing
